# Generated by Django 2.1.3 on 2019-01-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe_name', models.CharField(blank=True, max_length=45, null=True, verbose_name='classe')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Classes',
                'verbose_name': 'Classe',
            },
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(blank=True, max_length=45, null=True, verbose_name='Section')),
                ('is_active', models.BooleanField(default=True)),
                ('classe', models.ManyToManyField(blank=True, related_name='section_classe', to='configuration.Classes')),
            ],
            options={
                'verbose_name_plural': 'Sections',
                'verbose_name': 'Section',
            },
        ),
    ]
