# Generated by Django 2.1.3 on 2019-05-03 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_location_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectsSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.CharField(blank=True, max_length=10)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='configuration.Classes')),
            ],
        ),
        migrations.AddField(
            model_name='subjects',
            name='code',
            field=models.CharField(default='ABC', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subjects',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='subjectsset',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='configuration.Subjects'),
        ),
    ]
