# Generated by Django 2.1.3 on 2019-05-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_auto_20190503_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='classe_subjects', through='configuration.SubjectsSet', to='configuration.Subjects'),
        ),
    ]
