# Generated by Django 2.1.3 on 2019-05-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_subjectsset_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
