# Generated by Django 2.1.3 on 2019-05-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_subjects_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='section_name',
            field=models.CharField(default='ABC', max_length=45, verbose_name='Section'),
            preserve_default=False,
        ),
    ]
