# Generated by Django 2.1.3 on 2019-05-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_auto_20190508_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sections',
            name='classe',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='capacity',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
