# Generated by Django 2.1.3 on 2019-05-15 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20190515_0620'),
        ('configuration', '0008_auto_20190515_0620'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sections',
        ),
    ]
