# Generated by Django 2.1.3 on 2018-12-14 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20181214_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplines',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_type', to='student.Discipline_type'),
        ),
    ]
