# Generated by Django 2.1.3 on 2018-12-09 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0002_sections_classe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrivals_Departures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Departure'), (1, 'Arrival')])),
                ('justification', models.TextField(blank=True, null=True)),
                ('apply_on_date', models.DateField(null=True, verbose_name='Apply on date')),
                ('apply_on_time', models.TimeField(null=True, verbose_name='Apply on time')),
                ('is_excused', models.BooleanField(default=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_arrivals_departures', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_arrivals_departures', to='student.Student_hasDocs')),
                ('last_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrivals_departures_updated_by', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_arrivals_departures', to='student.Student')),
            ],
            options={
                'ordering': ('-updated_at',),
                'verbose_name_plural': 'Arrivals Departures',
                'verbose_name': 'Arrival Departure',
            },
        ),
        migrations.CreateModel(
            name='Attendances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(blank=True, choices=[(1, 'Present'), (0, 'Absent')], null=True)),
                ('motif', models.TextField(blank=True, null=True)),
                ('start_at', models.DateField(null=True, verbose_name='Start at')),
                ('end_at', models.DateField(null=True, verbose_name='End at')),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_attendance', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_attendance', to='student.Student_hasDocs')),
                ('last_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_updated_by', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='student.Student')),
            ],
            options={
                'ordering': ('-updated_at',),
                'verbose_name_plural': 'Attendances',
                'verbose_name': 'Attendance',
            },
        ),
        migrations.CreateModel(
            name='Discipline_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sanction', models.CharField(max_length=100, null=True, verbose_name='Sanction')),
                ('start_date', models.BooleanField(default=True)),
                ('end_date', models.BooleanField(default=True)),
                ('start_time', models.BooleanField(default=True)),
                ('end_time', models.BooleanField(default=False)),
                ('repeatable', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('sanction',),
                'verbose_name_plural': "Discipline's types",
                'verbose_name': "Discipline's type",
            },
        ),
        migrations.CreateModel(
            name='Disciplines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (2, 'Done'), (3, 'Cancelled')], default=1)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_created_by', to=settings.AUTH_USER_MODEL)),
                ('issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_issuer', to=settings.AUTH_USER_MODEL)),
                ('last_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_updated_by', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_discipine', to='student.Student')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_type', to='student.Discipline_type')),
            ],
            options={
                'ordering': ('-updated_at',),
                'verbose_name_plural': 'Disciplines',
                'verbose_name': 'Discipline',
            },
        ),
        migrations.CreateModel(
            name='Disciplines_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('finish_time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_detail_created_by', to=settings.AUTH_USER_MODEL)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_detail', to='student.Disciplines')),
                ('last_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_detail_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Disciplines details',
                'verbose_name': 'Discipline details',
            },
        ),
    ]
