# Generated by Django 2.1.3 on 2018-12-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_country_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='parents',
            name='is_InCharge',
            field=models.BooleanField(default=False),
        ),
    ]
