# Generated by Django 2.1.3 on 2018-12-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_parents_is_incharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='is_ICE',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='relationship',
            name='is_InCharge',
            field=models.BooleanField(default=False),
        ),
    ]
