# Generated by Django 2.1.3 on 2018-12-10 22:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20181210_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parents',
            name='is_ICE',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='is_InCharge',
        ),
        migrations.AlterField(
            model_name='student',
            name='ICE_details',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Emergency infos'),
        ),
    ]
