# Generated by Django 2.1.3 on 2018-12-11 21:58

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20181210_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplines',
            name='fact_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='disciplines',
            name='motif',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
