# Generated by Django 2.1.3 on 2018-12-14 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20181211_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplines',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_discipline', to='student.Student'),
        ),
    ]
