# Generated by Django 2.1.3 on 2018-12-14 19:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20181214_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendances',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='attendances',
            name='start_at',
        ),
        migrations.AddField(
            model_name='arrivals_departures',
            name='time_delta',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendances',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendances',
            name='finish_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendances',
            name='start_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='attendances',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arrivals_departures',
            name='apply_on_date',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Apply on date'),
        ),
        migrations.AlterField(
            model_name='arrivals_departures',
            name='apply_on_time',
            field=models.TimeField(default=django.utils.timezone.now, null=True, verbose_name='Apply on time'),
        ),
        migrations.AlterField(
            model_name='attendances',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_attendance', to='student.Student_hasDocs'),
        ),
        migrations.AlterField(
            model_name='attendances',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'Absent'), (1, 'Present')], null=True),
        ),
    ]
