# Generated by Django 2.1.3 on 2018-12-15 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20181214_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplines',
            options={'ordering': ('-updated_at', 'type'), 'verbose_name': 'Discipline', 'verbose_name_plural': 'Disciplines'},
        ),
    ]
