# Generated by Django 2.1.3 on 2018-12-15 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20181215_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplines',
            options={'ordering': ('-fact_date',), 'verbose_name': 'Discipline', 'verbose_name_plural': 'Disciplines'},
        ),
    ]
