# Generated by Django 2.1.3 on 2018-12-31 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_auto_20181230_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline_type',
            name='alert',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
