# Generated by Django 2.1.3 on 2019-01-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_discipline_type_alert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendances',
            options={'ordering': ('-start_date', '-updated_at'), 'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendances'},
        ),
        migrations.AlterField(
            model_name='attendances',
            name='type',
            field=models.IntegerField(choices=[(0, 'Absent'), (1, 'Present')], default=0),
        ),
    ]
