# Generated by Django 2.1.3 on 2019-05-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
