# Generated by Django 2.1.3 on 2019-05-08 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_auto_20190508_1454'),
        ('schedule', '0002_auto_20190508_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='classes',
        ),
        migrations.AddField(
            model_name='schedule',
            name='sections',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_sections', to='configuration.Sections'),
        ),
    ]
