# Generated by Django 2.1.3 on 2019-05-15 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_student_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0003_auto_20190508_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=45, verbose_name='Section')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Sections',
                'verbose_name': 'Section',
            },
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='sections',
        ),
        migrations.AddField(
            model_name='schedule',
            name='finishtAt',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='teacher',
        ),
        migrations.AddField(
            model_name='schedule',
            name='teacher',
            field=models.ManyToManyField(related_name='schedule_teachers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sections',
            name='schedule_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='schedule.Schedule'),
        ),
        migrations.AddField(
            model_name='sections',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_student', to='student.Student'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='schedule_student', through='schedule.Sections', to='student.Student'),
        ),
    ]
