# Generated by Django 2.1.3 on 2019-05-22 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20190515_0620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ('weekDay', 'startAt'), 'verbose_name': 'Schedule', 'verbose_name_plural': 'Schedule'},
        ),
    ]
