# Generated by Django 2.1.3 on 2018-12-07 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20181206_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='classes_ownership',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='sections_ownership',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='user',
        ),
        migrations.DeleteModel(
            name='User_details',
        ),
    ]
