# Generated by Django 2.1.3 on 2019-01-11 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student_notes',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_student_note', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student_notes',
            name='note_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_category', to='student.Note_Category'),
        ),
        migrations.AddField(
            model_name='student_notes',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_have_note', to='student.Student'),
        ),
        migrations.AddField(
            model_name='student_hasdocs',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentdoc_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student_hasdocs',
            name='last_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentdoc_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student_hasdocs',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AddField(
            model_name='student_hascontacts',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentcontact_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student_hascontacts',
            name='last_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentcontact_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student_hascontacts',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_hascontact', to='student.Student'),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_address', to='student.Address'),
        ),
        migrations.AddField(
            model_name='student',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_classe', to='configuration.Classes'),
        ),
        migrations.AddField(
            model_name='student',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='last_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ManyToManyField(blank=True, related_name='student_parent', through='student.Relationship', to='student.Parents'),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_section', to='configuration.Sections'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_membership', to='student.Parents'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_membership', to='student.Student'),
        ),
        migrations.AddField(
            model_name='parents',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_address', to='student.Address'),
        ),
        migrations.AddField(
            model_name='parents',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parents',
            name='last_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parent_hascontacts',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parentcontact_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parent_hascontacts',
            name='last_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parentcontact_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parent_hascontacts',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_hascontact', to='student.Parents'),
        ),
        migrations.AddField(
            model_name='disciplines_details',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_detail_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplines_details',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_detail', to='student.Disciplines'),
        ),
        migrations.AddField(
            model_name='disciplines_details',
            name='last_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_detail_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplines',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplines',
            name='issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_issuer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplines',
            name='last_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplines',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_discipline', to='student.Student'),
        ),
        migrations.AddField(
            model_name='disciplines',
            name='type',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipline_type', to='student.Discipline_type'),
        ),
        migrations.AddField(
            model_name='attendances',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendances',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_attendance', to='student.Student_hasDocs'),
        ),
        migrations.AddField(
            model_name='attendances',
            name='last_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendances',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='student.Student'),
        ),
        migrations.AddField(
            model_name='arrivals_departures',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_arrivals_departures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arrivals_departures',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_arrivals_departures', to='student.Student_hasDocs'),
        ),
        migrations.AddField(
            model_name='arrivals_departures',
            name='last_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrivals_departures_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arrivals_departures',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_arrivals_departures', to='student.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('street', 'city')},
        ),
    ]
